### ISSUE TITLE
Running as a service

### ISSUE THREAD

**Issue by JHFreeman** [cmd430/tv-movie-api#4]
What is the recommended way to run this as a service? pm2, upstart, or something else? I'm having an issue running from upstart and pm2, if you have some suggestions I'd be open to try something else. On ubuntu

**Comment by cmd430** [comment]
i just run it in a separate terminal (using tmux) it should just run in the background by itself fine

**Comment by JHFreeman** [comment]
I don't have a persistent connection to my server so when i log out the process dies so that approach won't work.

I have it set to run with upstart on ubuntu I get https://gist.github.com/JHFreeman/986ccef139a79890271f5c2e039f8c73 output in a loop

https://gist.github.com/JHFreeman/2e70cc5d157257b7f3ca7ca9d3689764 is the script to start the as a service, I'm not sure what I am doing wrong but any assistance would be appreciated.

**Comment by cmd430** [comment]
Tmux creates a muxed terminal, if you start the server from tmux and then detach from it you can logout and it will run in the background without stopping

I.E

`$ tmux`

`$ npm start`

Then press CTRL+B 

Then Press D (after releasing CTRL+B) you can now safely logout / close ssh

To get back to the session when you login use

`$ tmux a -t 0`

**Comment by JHFreeman** [comment]
Great, thanks
