### ISSUE TITLE
No covers on Movies

### ISSUE THREAD

**Issue by soavarice** [cmd430/tv-movie-api#5]
<img width="1680" alt="screen shot 2016-04-15 at 11 30 23 pm" src="https://cloud.githubusercontent.com/assets/16437290/14574103/1895997a-0362-11e6-8194-4d66a10eeda0.png">

{"server":"TV Movie API","status":"Scraping x264HDTV","totalMovies":4658,"totalShows":2029,"updated":1460746800,"updateTook":"2h 5m 17s","uptime":22462,"version":"1.2.1","repo":"https://github.com/cmd430/tv-movie-api.git","logs":{"warning":"/logs/warning","error":"/logs/error"}}

**Comment by cmd430** [comment]
If you load `/movies/1` from the API do you see links to images? 

could you please show what links they are if any (just one set should do I.e first 3)

**Comment by soavarice** [comment]
{"_id":"tt0926084","imdb_id":"tt0926084","title":"Harry Potter and the Deathly Hallows: Part 1","year":"2010","slug":"harry-potter-and-the-deathly-hallows-part-1-2010","synopsis":"The end begins as Harry, Ron, and Hermione walk away from their last year at Hogwarts to find and destroy the remaining Horcruxes, putting an end to Voldemort's bid for immortality. But with Harry's beloved Dumbledore dead and Voldemort's unscrupulous Death Eaters on the loose, the world is more dangerous than ever.","runtime":"146","rating":{"hated":100,"loved":100,"votes":9254,"watching":1,"percentage":80},"country":"en","last_updated":1460793495515,"images":{"fanart":"https://walter.trakt.us/images/movies/000/007/228/fanarts/original/03d576d04e.jpg","poster":"https://walter.trakt.us/images/movies/000/007/228/posters/original/cb528ca0db.jpg","banner":"https://walter.trakt.us/images/movies/000/007/228/banners/original/db8a964620.jpg"},"released":1290124800,"trailer":"http://youtube.com/watch?v=YbfMgvgR9NI","certification":"PG-13","torrents":{"1080p":{"url":"magnet:?xt=urn:btih:B214CBCCCC9FD627357BC8F38C58922349FB57FB&dn=harry+potter+and+the+deathly+hallows+part+1+2010+1080p+bluray+x264+dd5+1+fgt&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce","seeds":5,"peers":8,"provider":"Z0n321"}},"__v":0,"genres":["adventure","fantasy","family"]}

**Comment by cmd430** [comment]
hmm the links from the api work, i.e https://walter.trakt.us/images/movies/000/007/228/posters/original/cb528ca0db.jpg is loading fine in browser for me, im not too sure what your issue is

**Comment by soavarice** [comment]
Can be becacause im using old original 3.8-5 version?

**Comment by cmd430** [comment]
can you load the last link in your browser ? if so then possibly, i have no way to test though sorry (im working on my own project using the api and its loading covers just fine)
