### ISSUE TITLE
TV Shows do not update after initial scrape

### ISSUE THREAD

**Issue by FreedomFaighter** [cmd430/tv-movie-api#6]
After the first scrape on a fresh db, the shows do not add episodes, I have to stop the service, drop the database, then start it again and let it cycle once to see new episodes.

**Comment by cmd430** [comment]
could you please tell me your setup as I'm unable to reproduce this on my server sorry

**Comment by FreedomFaighter** [comment]
mongo v2.4.9
node 5.10.1
one thing i've noticed is that after cycling through the first three scrapers (KATmovies,KATshows,eztv) the output on the screen becomes very slow and there are pauses before going to the next provider. When it finds a tv show that is already in the database it gives a message that it is already there, I'm not sure if it fails to update at that point.

commit 5e1954a1ec6b7b714b71e34be2e047786e415300

**Comment by cmd430** [comment]
Ok first thing to try is update mongo to 3.0+ then let me know if you still have any issues

**Comment by FreedomFaighter** [comment]
Issue is resolved by upgrading to mongo 3.2.5
